### ISSUE TITLE
Создание навигации

### ISSUE THREAD

**Issue by DratskayaMaria** [DratskayaMaria/wovie#21]
Добавить навигацию согласно требованиям:

- F_Main_AboutFilm,
- F_Search_SearchScreen,
- F_Search_FromSearchToFilmDetails,
- F_Bookmarks_BookmarksScreen
- F_Actors_ActorsScreen

Ссылка на спецификацию: https://docs.google.com/document/d/1oNs12tsI2FYuw-k4JXHtwptDwc1mgNPui_rWidoRFUo/edit

**Comment by fedorovasofiya** [comment]
добавила описание
