### ISSUE TITLE
Добавить верстку экрана закладок

### ISSUE THREAD

**Issue by fedorovasofiya** [DratskayaMaria/wovie#8]
Сделать верстку главного экрана согласно требованиям спецификации (https://docs.google.com/document/d/1oNs12tsI2FYuw-k4JXHtwptDwc1mgNPui_rWidoRFUo/edit) F_Bookmarks_FilmInfo и F_Bookmarks_Info

**Comment by BurovnikovEvgeniy** [comment]
https://github.com/DratskayaMaria/wovie/pull/16
